/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *tree1;
  GtkWidget *res31;
  GtkWidget *text32;
  GtkWidget *entry4;
  GtkWidget *button2;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image23;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *radiobutton6;
  GSList *radiobutton6_group = NULL;
  GtkWidget *radb5;
  GtkWidget *button4;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image26;
  GtkWidget *label61;
  GtkWidget *b17;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image22;
  GtkWidget *label56;
  GtkWidget *bres1;
  GtkWidget *image20;
  GtkWidget *label2;
  GtkWidget *fixed3;
  GtkWidget *text2;
  GtkWidget *text3;
  GtkWidget *text4;
  GtkWidget *text5;
  GtkWidget *text6;
  GtkWidget *text7;
  GtkWidget *ent3;
  GtkWidget *text28;
  GtkWidget *ent10;
  GtkWidget *combobox1;
  GtkWidget *entry1;
  GtkWidget *textview37;
  GtkWidget *treeview2;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkWidget *comboboxentry1;
  GtkWidget *button1;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image25;
  GtkWidget *label60;
  GtkWidget *checb7;
  GtkWidget *checb9;
  GtkWidget *labeladdres;
  GtkWidget *button3;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image24;
  GtkWidget *label59;
  GtkWidget *label45;
  GtkWidget *label48;
  GtkWidget *label44;
  GtkWidget *label47;
  GtkWidget *label43;
  GtkWidget *label46;
  GtkWidget *label3;
  GtkWidget *fixed6;
  GtkWidget *text15;
  GtkWidget *text16;
  GtkWidget *text17;
  GtkWidget *text33;
  GtkWidget *text35;
  GtkWidget *text37;
  GtkWidget *text38;
  GtkWidget *ent11;
  GtkWidget *ent13;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *textview38;
  GtkWidget *entry2;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *but19;
  GtkWidget *image21;
  GtkWidget *but14;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image14;
  GtkWidget *label36;
  GtkWidget *comboboxentry2;
  GtkWidget *checkb1;
  GtkWidget *checkb2;
  GtkWidget *textview36;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  tree1 = gtk_tree_view_new ();
  gtk_widget_show (tree1);
  gtk_fixed_put (GTK_FIXED (fixed2), tree1, 48, 192);
  gtk_widget_set_size_request (tree1, 1072, 232);

  res31 = gtk_text_view_new ();
  gtk_widget_show (res31);
  gtk_fixed_put (GTK_FIXED (fixed2), res31, 296, 136);
  gtk_widget_set_size_request (res31, 176, 26);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (res31)), _("          reservation_id"), -1);

  text32 = gtk_text_view_new ();
  gtk_widget_show (text32);
  gtk_fixed_put (GTK_FIXED (fixed2), text32, 368, 520);
  gtk_widget_set_size_request (text32, 304, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text32)), _("                  Do you really want to delete ?"), -1);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 480, 136);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 504, 424);
  gtk_widget_set_size_request (button2, 88, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button2), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox17), image23, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Display"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox17), label57, FALSE, FALSE, 0);

  label58 = gtk_label_new (_("label58"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed2), label58, 952, 584);
  gtk_widget_set_size_request (label58, 368, 33);

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Yes"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton6, 592, 560);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radb5 = gtk_radio_button_new_with_mnemonic (NULL, _("No"));
  gtk_widget_show (radb5);
  gtk_fixed_put (GTK_FIXED (fixed2), radb5, 376, 560);
  gtk_widget_set_size_request (radb5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radb5), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radb5));

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 464, 592);
  gtk_widget_set_size_request (button4, 80, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button4), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image26 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox20), image26, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("confirm"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox20), label61, FALSE, FALSE, 0);

  b17 = gtk_button_new ();
  gtk_widget_show (b17);
  gtk_fixed_put (GTK_FIXED (fixed2), b17, 456, 632);
  gtk_widget_set_size_request (b17, 88, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (b17), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox16), image22, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox16), label56, FALSE, FALSE, 0);

  bres1 = gtk_button_new ();
  gtk_widget_show (bres1);
  gtk_fixed_put (GTK_FIXED (fixed2), bres1, 640, 136);
  gtk_widget_set_size_request (bres1, 66, 29);

  image20 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (bres1), image20);

  label2 = gtk_label_new (_("LISTE OF RESERV"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);
  gtk_misc_set_alignment (GTK_MISC (label2), 0.64, 0.5);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  text2 = gtk_text_view_new ();
  gtk_widget_show (text2);
  gtk_fixed_put (GTK_FIXED (fixed3), text2, 16, 152);
  gtk_widget_set_size_request (text2, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text2)), _("              parking_id"), -1);

  text3 = gtk_text_view_new ();
  gtk_widget_show (text3);
  gtk_fixed_put (GTK_FIXED (fixed3), text3, 16, 200);
  gtk_widget_set_size_request (text3, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text3)), _("          number_place  "), -1);

  text4 = gtk_text_view_new ();
  gtk_widget_show (text4);
  gtk_fixed_put (GTK_FIXED (fixed3), text4, 16, 240);
  gtk_widget_set_size_request (text4, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text4)), _("              license_ plate"), -1);

  text5 = gtk_text_view_new ();
  gtk_widget_show (text5);
  gtk_fixed_put (GTK_FIXED (fixed3), text5, 16, 312);
  gtk_widget_set_size_request (text5, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text5)), _("                start Date"), -1);

  text6 = gtk_text_view_new ();
  gtk_widget_show (text6);
  gtk_fixed_put (GTK_FIXED (fixed3), text6, 16, 400);
  gtk_widget_set_size_request (text6, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text6)), _("                 end Date"), -1);

  text7 = gtk_text_view_new ();
  gtk_widget_show (text7);
  gtk_fixed_put (GTK_FIXED (fixed3), text7, 16, 488);
  gtk_widget_set_size_request (text7, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text7)), _("        number _hours"), -1);

  ent3 = gtk_entry_new ();
  gtk_widget_show (ent3);
  gtk_fixed_put (GTK_FIXED (fixed3), ent3, 264, 240);
  gtk_widget_set_size_request (ent3, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ent3), 8226);

  text28 = gtk_text_view_new ();
  gtk_widget_show (text28);
  gtk_fixed_put (GTK_FIXED (fixed3), text28, 24, 96);
  gtk_widget_set_size_request (text28, 192, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text28)), _("          reservation_id"), -1);

  ent10 = gtk_entry_new ();
  gtk_widget_show (ent10);
  gtk_fixed_put (GTK_FIXED (fixed3), ent10, 272, 96);
  gtk_widget_set_size_request (ent10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ent10), 8226);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 600, 56);
  gtk_widget_set_size_request (combobox1, 33, 31);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 272, 152);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  textview37 = gtk_text_view_new ();
  gtk_widget_show (textview37);
  gtk_fixed_put (GTK_FIXED (fixed3), textview37, 32, 568);
  gtk_widget_set_size_request (textview37, 184, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview37)), _("                  message"), -1);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview2, 616, 280);
  gtk_widget_set_size_request (treeview2, 360, 256);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton4, 264, 312);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton5, 368, 312);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 2024, 2030, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton6, 488, 312);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton7, 272, 400);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton8, 384, 400);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (1, 2024, 2030, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton9, 488, 400);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  spinbutton17_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_show (spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton17, 272, 488);
  gtk_widget_set_size_request (spinbutton17, 60, 27);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry1, 272, 200);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("5"));

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed3), button1, 728, 536);
  gtk_widget_set_size_request (button1, 88, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button1), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox19), image25, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("display"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox19), label60, FALSE, FALSE, 0);

  checb7 = gtk_check_button_new_with_mnemonic (_("SMS"));
  gtk_widget_show (checb7);
  gtk_fixed_put (GTK_FIXED (fixed3), checb7, 352, 568);
  gtk_widget_set_size_request (checb7, 72, 24);

  checb9 = gtk_check_button_new_with_mnemonic (_("email"));
  gtk_widget_show (checb9);
  gtk_fixed_put (GTK_FIXED (fixed3), checb9, 256, 560);
  gtk_widget_set_size_request (checb9, 72, 24);

  labeladdres = gtk_label_new (_("label43"));
  gtk_widget_show (labeladdres);
  gtk_fixed_put (GTK_FIXED (fixed3), labeladdres, 784, 664);
  gtk_widget_set_size_request (labeladdres, 288, 33);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 280, 656);
  gtk_widget_set_size_request (button3, 66, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button3), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox18), image24, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("save"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox18), label59, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("Year"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed3), label45, 496, 376);
  gtk_widget_set_size_request (label45, 56, 25);

  label48 = gtk_label_new (_("Year"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed3), label48, 496, 296);
  gtk_widget_set_size_request (label48, 49, 17);

  label44 = gtk_label_new (_("Month"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed3), label44, 368, 288);
  gtk_widget_set_size_request (label44, 64, 25);

  label47 = gtk_label_new (_("Month"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed3), label47, 384, 376);
  gtk_widget_set_size_request (label47, 64, 17);

  label43 = gtk_label_new (_("Day"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed3), label43, 272, 376);
  gtk_widget_set_size_request (label43, 65, 25);

  label46 = gtk_label_new (_("Day"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 272, 288);
  gtk_widget_set_size_request (label46, 49, 17);

  label3 = gtk_label_new (_("ADD RESERVATION"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  text15 = gtk_text_view_new ();
  gtk_widget_show (text15);
  gtk_fixed_put (GTK_FIXED (fixed6), text15, 24, 360);
  gtk_widget_set_size_request (text15, 160, 24);
  gtk_text_view_set_justification (GTK_TEXT_VIEW (text15), GTK_JUSTIFY_CENTER);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text15)), _(" Start Date"), -1);

  text16 = gtk_text_view_new ();
  gtk_widget_show (text16);
  gtk_fixed_put (GTK_FIXED (fixed6), text16, 24, 440);
  gtk_widget_set_size_request (text16, 160, 24);
  gtk_text_view_set_justification (GTK_TEXT_VIEW (text16), GTK_JUSTIFY_CENTER);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text16)), _("End Date"), -1);

  text17 = gtk_text_view_new ();
  gtk_widget_show (text17);
  gtk_fixed_put (GTK_FIXED (fixed6), text17, 16, 520);
  gtk_widget_set_size_request (text17, 160, 24);
  gtk_text_view_set_justification (GTK_TEXT_VIEW (text17), GTK_JUSTIFY_CENTER);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text17)), _("Number of Hours"), -1);

  text33 = gtk_text_view_new ();
  gtk_widget_show (text33);
  gtk_fixed_put (GTK_FIXED (fixed6), text33, 72, 40);
  gtk_widget_set_size_request (text33, 160, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text33)), _("       reservation_id"), -1);

  text35 = gtk_text_view_new ();
  gtk_widget_show (text35);
  gtk_fixed_put (GTK_FIXED (fixed6), text35, 48, 136);
  gtk_widget_set_size_request (text35, 168, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text35)), _("        parking_id"), -1);

  text37 = gtk_text_view_new ();
  gtk_widget_show (text37);
  gtk_fixed_put (GTK_FIXED (fixed6), text37, 32, 200);
  gtk_widget_set_size_request (text37, 168, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text37)), _("          Number_ Place  "), -1);

  text38 = gtk_text_view_new ();
  gtk_widget_show (text38);
  gtk_fixed_put (GTK_FIXED (fixed6), text38, 32, 272);
  gtk_widget_set_size_request (text38, 192, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (text38)), _("              License Plate"), -1);

  ent11 = gtk_entry_new ();
  gtk_widget_show (ent11);
  gtk_fixed_put (GTK_FIXED (fixed6), ent11, 248, 40);
  gtk_widget_set_size_request (ent11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ent11), 8226);

  ent13 = gtk_entry_new ();
  gtk_widget_show (ent13);
  gtk_fixed_put (GTK_FIXED (fixed6), ent13, 264, 272);
  gtk_widget_set_size_request (ent13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ent13), 8226);

  label49 = gtk_label_new (_("Day"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed6), label49, 232, 328);
  gtk_widget_set_size_request (label49, 72, 25);

  label50 = gtk_label_new (_("Month"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed6), label50, 344, 328);
  gtk_widget_set_size_request (label50, 72, 25);

  label51 = gtk_label_new (_("Year"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed6), label51, 456, 328);
  gtk_widget_set_size_request (label51, 56, 25);

  label52 = gtk_label_new (_("Day"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed6), label52, 232, 416);
  gtk_widget_set_size_request (label52, 64, 17);

  label53 = gtk_label_new (_("Month"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed6), label53, 344, 408);
  gtk_widget_set_size_request (label53, 64, 25);

  label54 = gtk_label_new (_("Year"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed6), label54, 456, 408);
  gtk_widget_set_size_request (label54, 56, 24);

  label55 = gtk_label_new (_("label55"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed6), label55, 448, 600);
  gtk_widget_set_size_request (label55, 392, 33);

  textview38 = gtk_text_view_new ();
  gtk_widget_show (textview38);
  gtk_fixed_put (GTK_FIXED (fixed6), textview38, 24, 632);
  gtk_widget_set_size_request (textview38, 168, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview38)), _("          message"), -1);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed6), entry2, 248, 136);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton10, 240, 360);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  spinbutton11_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton11, 352, 360);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  spinbutton12_adj = gtk_adjustment_new (1, 2024, 2030, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton12, 464, 360);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  spinbutton13_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton13, 232, 440);
  gtk_widget_set_size_request (spinbutton13, 60, 27);

  spinbutton14_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton14, 352, 440);
  gtk_widget_set_size_request (spinbutton14, 60, 27);

  spinbutton15_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton15, 464, 440);
  gtk_widget_set_size_request (spinbutton15, 60, 27);

  spinbutton16_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton16, 224, 520);
  gtk_widget_set_size_request (spinbutton16, 60, 27);

  but19 = gtk_button_new ();
  gtk_widget_show (but19);
  gtk_fixed_put (GTK_FIXED (fixed6), but19, 416, 32);
  gtk_widget_set_size_request (but19, 48, 37);

  image21 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (but19), image21);

  but14 = gtk_button_new ();
  gtk_widget_show (but14);
  gtk_fixed_put (GTK_FIXED (fixed6), but14, 256, 744);
  gtk_widget_set_size_request (but14, 96, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (but14), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image14 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox11), image14, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("cofirm"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry2, 256, 200);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("5"));

  checkb1 = gtk_check_button_new_with_mnemonic (_("e-mail"));
  gtk_widget_show (checkb1);
  gtk_fixed_put (GTK_FIXED (fixed6), checkb1, 216, 640);
  gtk_widget_set_size_request (checkb1, 80, 24);

  checkb2 = gtk_check_button_new_with_mnemonic (_("SMS"));
  gtk_widget_show (checkb2);
  gtk_fixed_put (GTK_FIXED (fixed6), checkb2, 352, 640);
  gtk_widget_set_size_request (checkb2, 80, 24);

  textview36 = gtk_text_view_new ();
  gtk_widget_show (textview36);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), textview36);
  gtk_widget_set_size_request (textview36, 200, 32);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview36)), _("         MODIFY\n"), -1);

  g_signal_connect ((gpointer) tree1, "row_activated",
                    G_CALLBACK (on_tree1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) b17, "clicked",
                    G_CALLBACK (on_b17_clicked),
                    NULL);
  g_signal_connect ((gpointer) bres1, "clicked",
                    G_CALLBACK (on_bres1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) but19, "clicked",
                    G_CALLBACK (on_but19_clicked),
                    NULL);
  g_signal_connect ((gpointer) but14, "clicked",
                    G_CALLBACK (on_but14_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, tree1, "tree1");
  GLADE_HOOKUP_OBJECT (window1, res31, "res31");
  GLADE_HOOKUP_OBJECT (window1, text32, "text32");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, label57, "label57");
  GLADE_HOOKUP_OBJECT (window1, label58, "label58");
  GLADE_HOOKUP_OBJECT (window1, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window1, radb5, "radb5");
  GLADE_HOOKUP_OBJECT (window1, button4, "button4");
  GLADE_HOOKUP_OBJECT (window1, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window1, image26, "image26");
  GLADE_HOOKUP_OBJECT (window1, label61, "label61");
  GLADE_HOOKUP_OBJECT (window1, b17, "b17");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image22, "image22");
  GLADE_HOOKUP_OBJECT (window1, label56, "label56");
  GLADE_HOOKUP_OBJECT (window1, bres1, "bres1");
  GLADE_HOOKUP_OBJECT (window1, image20, "image20");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, text2, "text2");
  GLADE_HOOKUP_OBJECT (window1, text3, "text3");
  GLADE_HOOKUP_OBJECT (window1, text4, "text4");
  GLADE_HOOKUP_OBJECT (window1, text5, "text5");
  GLADE_HOOKUP_OBJECT (window1, text6, "text6");
  GLADE_HOOKUP_OBJECT (window1, text7, "text7");
  GLADE_HOOKUP_OBJECT (window1, ent3, "ent3");
  GLADE_HOOKUP_OBJECT (window1, text28, "text28");
  GLADE_HOOKUP_OBJECT (window1, ent10, "ent10");
  GLADE_HOOKUP_OBJECT (window1, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, textview37, "textview37");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window1, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window1, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window1, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window1, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window1, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window1, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window1, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1, label60, "label60");
  GLADE_HOOKUP_OBJECT (window1, checb7, "checb7");
  GLADE_HOOKUP_OBJECT (window1, checb9, "checb9");
  GLADE_HOOKUP_OBJECT (window1, labeladdres, "labeladdres");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window1, image24, "image24");
  GLADE_HOOKUP_OBJECT (window1, label59, "label59");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, label48, "label48");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, text15, "text15");
  GLADE_HOOKUP_OBJECT (window1, text16, "text16");
  GLADE_HOOKUP_OBJECT (window1, text17, "text17");
  GLADE_HOOKUP_OBJECT (window1, text33, "text33");
  GLADE_HOOKUP_OBJECT (window1, text35, "text35");
  GLADE_HOOKUP_OBJECT (window1, text37, "text37");
  GLADE_HOOKUP_OBJECT (window1, text38, "text38");
  GLADE_HOOKUP_OBJECT (window1, ent11, "ent11");
  GLADE_HOOKUP_OBJECT (window1, ent13, "ent13");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, label50, "label50");
  GLADE_HOOKUP_OBJECT (window1, label51, "label51");
  GLADE_HOOKUP_OBJECT (window1, label52, "label52");
  GLADE_HOOKUP_OBJECT (window1, label53, "label53");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, textview38, "textview38");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (window1, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (window1, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (window1, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (window1, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (window1, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (window1, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (window1, but19, "but19");
  GLADE_HOOKUP_OBJECT (window1, image21, "image21");
  GLADE_HOOKUP_OBJECT (window1, but14, "but14");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image14, "image14");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (window1, checkb1, "checkb1");
  GLADE_HOOKUP_OBJECT (window1, checkb2, "checkb2");
  GLADE_HOOKUP_OBJECT (window1, textview36, "textview36");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed7;
  GtkWidget *textview39;
  GtkWidget *button5;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window2), fixed7);

  textview39 = gtk_text_view_new ();
  gtk_widget_show (textview39);
  gtk_fixed_put (GTK_FIXED (fixed7), textview39, 112, 40);
  gtk_widget_set_size_request (textview39, 184, 56);

  button5 = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed7), button5, 168, 120);
  gtk_widget_set_size_request (button5, 66, 29);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window2, textview39, "textview39");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");

  return window2;
}

